import { accordion } from "./_accordion";
import { animation } from "./_animation";
import { common } from "./_common";
import { drawer } from "./_drawer";
import { slide } from "./_slide";
import { test } from "./_line";
import { header } from "./_header";
import { img } from "./_img";
import { textScroll } from "./_textScroll";
import { line } from "./_line";

accordion();
animation();
common();
drawer();
slide();
line();
textScroll();
img();
header();
test();
