// import { accordion } from "./_accordion";
import { animation } from "./_animation";
import { common } from "./_common";
import { drawer } from "./_drawer";
// import { slide } from "./_slide";
import { mv } from "./_mv";
import { line } from "./_line";
import { textScroll } from "./_textScroll";
import { img } from "./_img";
import { header } from "./_header";
import { timeline } from "./_timeline";

// accordion();
animation();
common();
drawer();
// slide();
mv();
line();
textScroll();
img();
timeline();
header();
// test();
